on:
  workflow_dispatch:
  push:
    branches: 
    - main

name: scrape-obgyn-profile

jobs:
  import-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3    
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true        

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::furrr
            any::rvest
            any::xopen

      - name: Import postal code data
        run: Rscript -e 'source("scrape_postal_code.R")'
        
      - name: Import obgyn data
        run: Rscript -e 'source("scrape_obgyn_profile.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/states_postalcodes_tbl.rds
          git add data/obgyn_profile.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
